version: "3"
services: 
    client:
        build:
            context: ./Client
            dockerfile: Dockerfile
        ports: 
            - "9000:80"
    api:
        build: 
            context: ./Server
            dockerfile: Dockerfile
        ports: 
            - "5000:80"
    sqldata:
        image: mcr.microsoft.com/mssql/server:2019-latest 


